#!/bin/sh

echo "Running inside container..."
echo "Current directory: $(pwd)"
echo "User: $(whoami)"
echo "Attempting to create test.txt..."
touch test.txt
ls -l test.txt

touch /home/openfoam/simulation/test.txt
ls -l /home/openfoam/simulation/test.txt

# Get and display the current directory of this script
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
echo "Running script in directory: $SCRIPT_DIR"

cd "$SCRIPT_DIR" || exit 1    # Ensure script runs from its own directory

# Create a file called test.txt and write "hello world" into it
FILE_PATH="$SCRIPT_DIR/test.txt"
echo "hello world" > "$FILE_PATH"
echo "Created test.txt at: $FILE_PATH"

# Print the content of the created file
echo "===== Content of test.txt ====="
cat "$FILE_PATH"
echo "================================"

FILE_PATH="$SCRIPT_DIR/Allclean"
echo "===== Content of Allclean ====="
cat "$FILE_PATH"
echo "================================"


# Source tutorial run functions
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

application=$(getApplication)

runApplication blockMesh
runApplication "$application" -functionObjects -writePhi -writep
runApplication foamPostProcess -func streamFunction

runApplication foamToVTK
#------------------------------------------------------------------------------

# Display first 50 lines of all log files
echo "===== Showing first 50 lines of all logs of OpenFOAM"
echo "===== Please check for any errors or warnings"
echo "===== If you need to see more lines, please open the log file directly"
find . -type f -name "log*" | while read -r log; do
    echo "---- $log ----"
    head -n 50 "$log"
    echo "--------------------------------------"
done
