#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh

runApplication createBaffles -overwrite
runApplication splitBaffles -overwrite

runApplication splitMeshRegions -cellZonesOnly -overwrite

rm -f 0/cellToRegion 0/*/cellToRegion constant/cellToRegion

runApplication -s fluid topoSet -dict system/topoSetDict -region fluid
runApplication -s solid topoSet -dict system/topoSetDict -region solid
runApplication -s roller topoSet -dict system/topoSetDict -region roller

! isTest "$@" && [ -n "$1" ] && mode=$1 || mode=parallel

case $mode in
    serial)
        runApplication createNonConformalCouples -overwrite
        runApplication foamRun
        ;;
    parallel | stitchSerial)
        runApplication createNonConformalCouples -overwrite
        runApplication decomposePar -allRegions -copyZero -cellProc
        runParallel foamMultiRun
        runApplication reconstructPar -allRegions
        ;;
    stitchParallel)
        runApplication decomposePar -allRegions -copyZero -cellProc
        runParallel createNonConformalCouples -overwrite
        runParallel foamMultiRun
        runApplication reconstructPar -allRegions
        ;;
    *)
        echo "Error: mode $mode not recognised"
        exit 1
        ;;
esac

paraFoam -touchAll

runApplication foamToVTK
#------------------------------------------------------------------------------

# Display first 50 lines of all log files
echo "===== Showing first 50 lines of all logs"
echo "===== Please check for any errors or warnings"
echo "===== If you need to see more lines, please open the log file directly"
find . -type f -name "log*" | while read -r log; do
    echo "---- $log ----"
    head -n 50 "$log"
    echo "--------------------------------------"
done
